import Link from "next/link";

export const metadata = {
  title: "Terms of Use · AfriCareer AI",
  description: "The terms that govern your use of AfriCareer AI.",
};

function Section({ title, children }) {
  return (
    <section className="mt-8">
      <h2 className="text-lg font-bold text-slate-900">{title}</h2>
      <div className="mt-2 space-y-3 text-sm leading-relaxed text-slate-600">{children}</div>
    </section>
  );
}

export default function Terms() {
  return (
    <main className="min-h-screen bg-white">
      <header className="border-b border-slate-100">
        <div className="mx-auto flex max-w-3xl items-center justify-between px-6 py-4">
          <Link href="/" className="text-lg font-extrabold tracking-tight text-slate-900">
            AfriCareer <span className="text-[var(--brand)]">AI</span>
          </Link>
          <Link href="/app" className="rounded-lg bg-[var(--brand)] px-4 py-2 text-sm font-semibold text-white transition hover:bg-[var(--brand-dark)]">Launch app</Link>
        </div>
      </header>

      <article className="mx-auto max-w-3xl px-6 py-12">
        <h1 className="text-3xl font-extrabold tracking-tight text-slate-900">Terms of Use</h1>
        <p className="mt-2 text-sm text-slate-400">Effective Date: July 2026</p>
        <p className="mt-6 text-sm leading-relaxed text-slate-600">
          By using AfriCareer AI (the &ldquo;Service&rdquo;), operated by Quantium Insights LLC, you agree to these terms.
          The Service is provided free of charge to support career and academic guidance for African youth and professionals.
        </p>

        <Section title="1. Guidance, not professional advice">
          <p>
            AfriCareer AI provides informational guidance generated by an AI system. It is <strong>not</strong> a substitute
            for professional legal, medical, financial, or immigration advice. Always verify important decisions with a
            qualified professional or the official source.
          </p>
        </Section>

        <Section title="2. AI outputs may contain errors">
          <p>
            AI responses can be incomplete or occasionally incorrect. While we ground answers in trusted frameworks and
            verify links in real time, you are responsible for reviewing outputs before relying on them. We do not guarantee
            any particular job, admission, scholarship, or other outcome.
          </p>
        </Section>

        <Section title="3. Acceptable use">
          <p>You agree not to use the Service for unlawful, harmful, or abusive purposes, or to attempt to disrupt or overload it. We may apply reasonable rate limits to keep the Service available for everyone.</p>
        </Section>

        <Section title="4. Third-party links">
          <p>The Service surfaces links to external job boards, courses, and organisations. These sites are operated by third parties and are provided for convenience; we are not responsible for their content or availability.</p>
        </Section>

        <Section title="5. Your content">
          <p>You retain rights to the content you submit and to the documents the Service generates for you. You are responsible for ensuring you have the right to submit any content you provide.</p>
        </Section>

        <Section title="6. Availability & changes">
          <p>The Service is provided on an &ldquo;as is&rdquo; and &ldquo;as available&rdquo; basis. We may update features, these terms, or discontinue parts of the Service. Continued use after changes means you accept the updated terms.</p>
        </Section>

        <Section title="7. Contact">
          <p>Questions about these terms? Email <a className="font-medium text-[var(--brand)] hover:underline" href="mailto:dramobionovo@quantiuminsights.com">dramobionovo@quantiuminsights.com</a> (Quantium Insights LLC).</p>
        </Section>

        <div className="mt-10 flex gap-4 border-t border-slate-100 pt-6 text-sm">
          <Link href="/privacy" className="font-medium text-[var(--brand)] hover:underline">Privacy Policy →</Link>
          <Link href="/" className="text-slate-400 hover:text-slate-600">← Back to home</Link>
        </div>
      </article>
    </main>
  );
}
